### ISSUE TITLE
hygiene?

### ISSUE THREAD

**Issue by AlexKnauth** [lexi-lambda/racket-curly-fn#3]
This fails:

``` racket
#lang curly-fn racket
(let ([lambda 5])
  (map #{+ % 1} '(1 2 3)))
```

If you want, you could use a similar approach to afl's [here](https://github.com/AlexKnauth/afl/blob/master/afl/reader.rkt#L128) or rackjure's [here](https://github.com/greghendershott/rackjure/blob/master/rackjure/lambda-reader.rkt#L14), or, if you want it to still work with Matthew Flatt's scope-set expander, you could do something like [this](https://github.com/AlexKnauth/afl/commit/d5522c650483db697ccf51b357bb6626bb976a01).

**Comment by lexi-lambda** [comment]
Yes, @mflatt has linked me to the thread wrt the new macro expander. Shorthand functions are already a bit of a hack, imo, so I'm not _terribly_ concerned about this sort of edge case behavior when no clear solution seems to exist.

As an example of how shorthand functions are hacky already, take this code as an example.

``` racket
(#{let ([%2 2]) (+ % %2)} 1)
```

Unfortunately, you get a runtime error because the function wants two arguments. This is not good behavior, but it's a side-effect of this all being handled at read-time rather than at expansion-time. Ideally, this could be implemented as a macro instead which simply scans the unbound identifiers instead of inspecting the datums and comparing them, but currently, I don't think that's possible.

For now, I'm content with some stupid behavior. These are designed to be used for super-simple functions, nothing more. If a good, general solution is found for this problem, I'll update this accordingly.

**Comment by AlexKnauth** [comment]
About `(#{let ([%2 2]) (+ % %2)} 1)`, I think it's better that it works at read-time, because then you don't have to worry about a macro expanding to an identifier that would add an extra argument or causing a capture that would take away an argument.  What you see is what you get, but what _that_ expands to is another matter. I think it makes sense that it requires two arguments but ends up ignoring the second one.

I do see what you're saying about being content the way it is, since they are meant to be used for super-simple functions. But, I also wonder if that's what some people originally thought of hygienic macros?

**Comment by lexi-lambda** [comment]
I agree that I'm all in favor of hygiene, and I agree that this is currently a subpar solution. If a clear single solution existed that didn't seem like a hack to me, I would be willing to implement it. However, especially with the new macro expander currently being fleshed out, I'm reluctant to commit to any particular paths, especially ones that would limit the functionality to one expander or the other.

As mentioned in the mailing list thread, this is probably an area where research could help. I think it's a good thing that rackjure and afl exist as well, since those can help to demonstrate varying approaches. For now, though, I'm willing to hold off on attempting a fix until a "proper" solution has been discovered, or at least until the changes occurring to macro expander have settled down.

**Comment by lexi-lambda** [comment]
Now fixed on HEAD thanks to mflatt's work. :smiley:
